### ISSUE TITLE
UN LOCODE namespaces

### ISSUE THREAD

**Issue by VladimirAlexiev** [uncefact/spec-jsonld#27]
ADAVL "Andorra la Vella" is published as https://service.unece.org/trade/uncefact/vocabulary/unlocode-ad/ADAVL.
- All other vocabs are published at single big pages, but I guess you found https://service.unece.org/trade/uncefact/vocabulary/unlocode/ to grow too big (Wikidata says over 100k entries, see https://www.wikidata.org/wiki/Property:P1937)
- Well, that's inconsistent
- To resolve LOCODE to this URL, one would have to split and manipulate the first two chars

The smart people at Wikidata can do such switcheroo
- see https://www.wikidata.org/wiki/Property:P3608
- eg BG200356710 (Ontotext) goes to https://wikidata-externalid-url.toolforge.org, which does some splitting and results in https://ec.europa.eu/taxation_customs/vies/vatResponse.html?memberStateCode=BG&number=200356710
  - (the specific toolforge URL is
`https://wikidata-externalid-url.toolforge.org/?p=3608&url_prefix=http://ec.europa.eu/taxation_customs/vies/vatResponse.html?memberStateCode=&id=BG200356710`)

But making consumers jump through hoops just ain't right.
If you do #26, that won't be necessary

**Comment by nissimsan** [comment]
@kshychko , this looks like a great input. Please run with this for inspiration on our dealing iwth locodes...

**Comment by nissimsan** [comment]
@VladimirAlexiev , @Fak3 , what would be the ideal URI you'd like to see?
`https://service.unece.org/trade/uncefact/vocabulary/unlocode/ADAVL`?

**Comment by kshychko** [comment]
According to the discussion on #105 the following approach is taken:
1. Define RDF Classes for UNLOCODE, Subdivision, Function. For Country "schema:Country" type can be used
2. Because there are codes in both UN/LOCODE and Subdivision code lists, separate namespaces are used for those and other entities.
3. The language is set to "en" for the labels without diacritics. It's impossible to determine the language for the names with diactics so the language is not specified there. - **To discuss**
4. As countries and subdivisions are ISO 3166-1 and ISO 3166-2 code lists we might need to think about publishing them separately from UNLCODE - **To discuss**
5. UNLOCODE list items don't always have the location defined, so it is possible that it is also missing in the vocabulary.

**Comment by kshychko** [comment]
The current outputs for discussion are available in https://github.com/uncefact/codes-locode/tree/main/vocab

**Comment by kshychko** [comment]
Subdiivision:
"TW","TPE","Taipei","special municipality"
LOCODE:
,"TW","TPE","Taipei","Taipei","TPE","1--45---","AI","1101",,"2502N 12131E",""

**Comment by nissimsan** [comment]
IATA codes are missing, but let's tackle that in a separate PR.

**Comment by nissimsan** [comment]
We did this: https://github.com/uncefact/spec-jsonld/pull/105
